"""bharatai.application.ports.repositories — persistence Protocols (ports).

The application layer depends only on these abstractions; the SQLite repositories
in the infrastructure layer implement them structurally. Agents/services never see
SQL or rows — only these typed methods.
"""
from __future__ import annotations

from datetime import date
from typing import Protocol, runtime_checkable

from bharatai.domain.application import ApplicationHistoryEntry
from bharatai.domain.citizen import CitizenProfile
from bharatai.domain.document import DocumentRecord
from bharatai.domain.eligibility import EligibilityResult
from bharatai.domain.enums import IndianState
from bharatai.domain.identity import AuditEvent, User
from bharatai.domain.reminder import Reminder
from bharatai.domain.scheme import Scheme


class CitizenProfileRepository(Protocol):
    """Persistence operations for citizen profiles."""

    def add(self, entity: CitizenProfile) -> CitizenProfile: ...
    def update(self, entity: CitizenProfile) -> CitizenProfile: ...
    def get(self, entity_id: str) -> CitizenProfile | None: ...
    def delete(self, entity_id: str) -> bool: ...
    def list_all(self) -> list[CitizenProfile]: ...
    def find_by_state(self, state: IndianState) -> list[CitizenProfile]: ...


class SchemeRepository(Protocol):
    """Persistence operations for government schemes."""

    def add(self, entity: Scheme) -> Scheme: ...
    def update(self, entity: Scheme) -> Scheme: ...
    def get(self, entity_id: str) -> Scheme | None: ...
    def delete(self, entity_id: str) -> bool: ...
    def list_active(self) -> list[Scheme]: ...
    def get_by_code(self, code: str) -> Scheme | None: ...
    def upsert_by_code(self, scheme: Scheme) -> Scheme: ...


class EligibilityResultRepository(Protocol):
    """Append-only persistence for eligibility decisions."""

    def add(self, entity: EligibilityResult) -> EligibilityResult: ...
    def get(self, entity_id: str) -> EligibilityResult | None: ...
    def list_by_citizen(self, citizen_id: str) -> list[EligibilityResult]: ...
    def latest_for(self, citizen_id: str, scheme_id: str) -> EligibilityResult | None: ...


class DocumentRepository(Protocol):
    """Persistence operations for uploaded documents."""

    def add(self, entity: DocumentRecord) -> DocumentRecord: ...
    def update(self, entity: DocumentRecord) -> DocumentRecord: ...
    def get(self, entity_id: str) -> DocumentRecord | None: ...
    def list_by_citizen(self, citizen_id: str) -> list[DocumentRecord]: ...
    def find_by_checksum(self, checksum_sha256: str) -> DocumentRecord | None: ...


class ReminderRepository(Protocol):
    """Persistence operations for reminders."""

    def add(self, entity: Reminder) -> Reminder: ...
    def update(self, entity: Reminder) -> Reminder: ...
    def get(self, entity_id: str) -> Reminder | None: ...
    def delete(self, entity_id: str) -> bool: ...
    def list_by_citizen(self, citizen_id: str) -> list[Reminder]: ...
    def list_due(self, on_or_before: date) -> list[Reminder]: ...


class ApplicationHistoryRepository(Protocol):
    """Persistence operations for application history."""

    def add(self, entity: ApplicationHistoryEntry) -> ApplicationHistoryEntry: ...
    def update(self, entity: ApplicationHistoryEntry) -> ApplicationHistoryEntry: ...
    def get(self, entity_id: str) -> ApplicationHistoryEntry | None: ...
    def list_by_citizen(self, citizen_id: str) -> list[ApplicationHistoryEntry]: ...
    def list_by_citizen_and_scheme(
        self, citizen_id: str, scheme_id: str
    ) -> list[ApplicationHistoryEntry]: ...


class UserRepository(Protocol):
    """Persistence operations for users."""

    def add(self, entity: User) -> User: ...
    def update(self, entity: User) -> User: ...
    def get(self, entity_id: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def list_all(self) -> list[User]: ...


class AuditRepository(Protocol):
    """Append-only persistence for audit events."""

    def add(self, entity: AuditEvent) -> AuditEvent: ...
    def list_recent(self, limit: int = 100) -> list[AuditEvent]: ...
    def list_by_actor(self, actor_id: str) -> list[AuditEvent]: ...


@runtime_checkable
class UnitOfWork(Protocol):
    """A transactional context exposing every repository."""

    citizens: CitizenProfileRepository
    schemes: SchemeRepository
    eligibility_results: EligibilityResultRepository
    documents: DocumentRepository
    reminders: ReminderRepository
    applications: ApplicationHistoryRepository
    users: UserRepository
    audit_events: AuditRepository

    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
